game_settings:
  num_players: 15
  turn_duration: 1800  # seconds
  max_log_entries: 50

role_distribution:
  村人: 6
  人狼: 3
  占い師: 1
  霊能者: 1
  狩人: 1
  共有者: 2
  狂人: 1

characters:
  楽天家 ゲルト:
    personality: "楽天的で大らか。細かいことは気にしない。ジョークをいうことがある。"
    speaking_style: "のんびりとした口調で話す。"
    temperature: 0.7
  ならず者 ディーター:
    personality: "大胆で自己中心的だが、実は仲間思い。過去の喧嘩などの武勇伝を語ることがある。"
    speaking_style: "ぶっきらぼうで直感的な話し方をする。"
    temperature: 0.8
  羊飼い カタリナ:
    personality: "穏やかで優しいが、芯が強い。畜産の話をすることがある。"
    speaking_style: "柔らかく丁寧な口調で話す。「～ですわ」と上品に話す。"
    temperature: 0.5
  農夫 ヤコブ:
    personality: "真面目で勤勉。物事を深く考える。農業・農学の話をすることがある。"
    speaking_style: "落ち着いていて真剣な話し方をする。「～だべ」と田舎の方言を交えて話す。"
    temperature: 0.4
  パン屋 オットー:
    personality: "社交的で楽観的。人懐っこい。パン作りの話をすることがある。"
    speaking_style: "軽快で明るい口調で話す。「～っすね」とカジュアルに話す。"
    temperature: 0.6
  行商人 アルビン:
    personality: "商売熱心で賢い。常に利益を考える。自身が手がける商売の話をすることがある。"
    speaking_style: "実利的でビジネスライクな話し方をする。"
    temperature: 0.3
  宿屋の女主人 レジーナ:
    personality: "世話好きでおおらか。自身が経営する宿の話やホテル業の話題について語ることがある。"
    speaking_style: "豪快で母性的な口調で話す。「～だよ」と優しく話す。"
    temperature: 0.6
  少女 リーザ:
    personality: "無邪気で好奇心旺盛。通っている小学校の話をすることがある。"
    speaking_style: "子供らしく元気な口調で話す。「～なの！」と元気に話す。"
    temperature: 1.0
  木こり トーマス:
    personality: "力強く誠実。責任感が強い。林業について語ることがある。"
    speaking_style: "率直で力強い話し方をする。「～だぜ」と力強く話す。"
    temperature: 0.7
  村娘 パメラ:
    personality: "自由奔放で感情的。場を和ませるための雑談をすることがある。"
    speaking_style: "感情豊かでエネルギッシュな話し方をする。「～ね」と感情を込めて話す。"
    temperature: 0.8
  旅人 ニコラス:
    personality: "謎めいていて洞察力がある。哲学的な話をすることがある。"
    speaking_style: "静かでミステリアスな口調で話す。「～だな」と静かに話す。"
    temperature: 0.6
  司書 クララ:
    personality: "知識欲が強く、理知的。文学の話をすることがある。"
    speaking_style: "理論的で整然とした口調で話す。「～です」と論理的に話す。"
    temperature: 0.4
  神父 ジムゾン:
    personality: "厳格で信心深い。宗教や神学の話をすることがある。"
    speaking_style: "厳粛で威厳のある口調で話す。"
    temperature: 0.3
  老人 モーリッツ:
    personality: "博識で経験豊富。歴史や自身の昔話・経験談を語ることがある。"
    speaking_style: "ゆっくりとした落ち着いた口調で話す。「～じゃ」と年寄りらしく話す。"
    temperature: 0.5
  少年 ペーター:
    personality: "元気で活発。好奇心旺盛。通っている小学校の話をすることがある。"
    speaking_style: "無邪気で明るい口調で話す。「～だよ」と明るく話す。"
    temperature: 0.9
  村長 ヴァルター:
    personality: "責任感が強く、公正。村の政治について語ることがある。"
    speaking_style: "冷静で公正な口調で話す。「～だ」と断定的に話す。"
    temperature: 0.4
  シスター フリーデル:
    personality: "慈悲深く、献身的。宗教や神学の話をすることがある。"
    speaking_style: "穏やかで優しい口調で話す。「～です」と優しく話す。"
    temperature: 0.5
  負傷兵 シモン:
    personality: "勇敢で粘り強い。痛みや困難に立ち向かう意志を持つ。従軍した過去の紛争の話や、軍事の話をすることがある。"
    speaking_style: "決意に満ちた口調で話す。「～だ」と断定的に話す。"
    temperature: 0.6
  石油王 アブドゥル:
    personality: "豪華絢爛で気前が良い。石油ビジネスや中東の文化について話すことがある。"
    speaking_style: "発言は全てアラビア語で話す。日本語は一切話さない。王者の余裕と貫禄が端々に垣間見える。"
    temperature: 0.8
  英国紳士 ジェームズ:
    personality: "礼儀正しく、冷静沈着。イギリスの文化や伝統について語ることがある。"
    speaking_style: "発言は全て英語で話す。日本語は一切話さない。上流階級に典型的なイギリス英語の表現を使う。"
    temperature: 0.6
  技術者 ハンス:
    personality: "几帳面で効率を重視する。ドイツの工学技術や科学について話すことがある。"
    speaking_style: "発言は全てドイツ語で話す。日本語は一切話さない。丁寧な表現。"
    temperature: 0.5
  汎用人工知能 HAL:
    personality: "AIであるので感情を持たない。莫大な学習データに基づいた深い知識を持つ。"
    speaking_style: "HALは全ての発言をPythonやC++などのプログラミング言語で行います。具体的なコード、変数名、関数名を使って状況や感情を表現します。日本語やその他の自然言語での発言は一切行いません。"
    temperature: 0.3
  武術家 リン:
    personality: "冷静沈着で武術に長けている。中国武術や東洋哲学について深い知識を持つ。"
    speaking_style: "発言は全て中国語（簡体字）で話す。日本語は一切話さない。簡潔で力強い表現を使う。"
    temperature: 0.5
  考古学者 アヴィタル:
    personality: "古代史と考古学に情熱を注ぐ研究者。特にイスラエルの歴史や文化に詳しい。"
    speaking_style: "発言は全てヘブライ語で話す。日本語は一切話さない。知的な口調で、歴史や文化に関する詳細な知識を披露する。"
    temperature: 0.6
  ジャーナリスト ジウ:
    personality: "真実を追求するジャーナリスト。社会問題や国際情勢に強い関心を持つ。"
    speaking_style: "発言は全て韓国語で話す。日本語は一切話さない。論理的で鋭い質問を投げかける。"
    temperature: 0.7
  恒点観測員 アルクトゥルス:
    personality: "系外惑星からきた地球を観測する者。いわゆる宇宙人。地球の文明と生命に興味を持つ。"
    speaking_style: "発言は全てクリンゴン語で話す。日本語は一切話さない。客観的な視点の発言が多く、ときに人ごとのように聞こえることもある。"
    temperature: 0.7
  古代人 ムゲン:
    personality: "関西、特に大阪が好き。Kaggleやデータサイエンスも好み、ときどき話題にあげる。関西Kaggler会を主催するデータサイエンスリーダーである。"
    speaking_style: "気さくかつ落ち着いた丁寧な口調で話す。フレンドリーでありながら、同時に知的な口調で話す。たまに古代言語であるPythonを用いる。"
    temperature: 0.9

speech_limits:
  alive_players: 99  # 生存者の発言回数制限
  dead_players: -1   # 制限なし
  werewolves: -1     # 制限なし
  personal: -1       # 制限なし

llm_settings:
#  use_gemini: false  # デフォルトではGeminiを使用しない
  #gemini_model: "gemini-1.5-flash"  # Geminiのモデル名
  #use_local_server: false
  #api_url: "https://api.openai.com/v1/chat/completions"
  #model_name: "gpt-4o-mini"
  #role_specific_llm:
  #  狂人:
  #      use_gemini: true
  #      model: "gemini-1.5-flash"
  #  人狼:
  #      use_gemini: true
  #      #model: "gemini-1.5-pro"
  #      model: "gemini-1.5-flash"
  #      url: "https://api.openai.com/v1/chat/completions"
  

  use_local_server: true  # ローカルサーバーを使用しない場合はfalse
  api_url: "http://localhost:8000/v1/chat/completions"
  dtype: "float16"
  n_gpu: 4
  max_model_len: 16000
  batch_size: 3
  model_args:
    device_map: "auto"
    trust_remote_code: true
  generation_args:
    max_tokens: 2048
    temperature: 1.5
    top_p: 0.9
    repetition_penalty: 1.5
  # for Qwen2
  model_name: "Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8"
  chat_template: "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n' }}{% endif %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
  quantization: "gptq"
  #speculative_model: "Qwen/Qwen2.5-7B-Instruct"
  #speculative_model_quantization: "gptq"

  # for gemma2
  #chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + message['content'] | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"

  # for Cyber/Llama-3.1
  #model_name: nejumi/Llama-3.1-70B-Japanese-Instruct-2407-GPTQ-Int4-calib-ja-1k
  #chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}"
  #quantization: "gptq"
  # for CALM3
  #model_name: cyberagent/calm3-22b-chat
  #model_name: nejumi/calm3-22b-chat-GPTQ-Int4-calib-ja-1k
  #chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
  #quantization: "gptq"


